// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configurations.sql

package sqlc

import (
	"context"
)

const getConfigurationByKey = `-- name: GetConfigurationByKey :one
SELECT id, key, value, created_at, updated_at FROM configurations WHERE key = $1
`

func (q *Queries) GetConfigurationByKey(ctx context.Context, key string) (Configuration, error) {
	row := q.db.QueryRow(ctx, getConfigurationByKey, key)
	var i Configuration
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllConfigurations = `-- name: ListAllConfigurations :many
SELECT id, key, value, created_at, updated_at FROM configurations ORDER BY created_at DESC
`

func (q *Queries) ListAllConfigurations(ctx context.Context) ([]Configuration, error) {
	rows, err := q.db.Query(ctx, listAllConfigurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Configuration
	for rows.Next() {
		var i Configuration
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfigurationValue = `-- name: UpdateConfigurationValue :exec
UPDATE configurations
SET value = $2,
    updated_at = NOW()
WHERE key = $1
`

type UpdateConfigurationValueParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpdateConfigurationValue(ctx context.Context, arg UpdateConfigurationValueParams) error {
	_, err := q.db.Exec(ctx, updateConfigurationValue, arg.Key, arg.Value)
	return err
}
