// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Configuration struct {
	ID        int64            `json:"id"`
	Key       string           `json:"key"`
	Value     string           `json:"value"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Project struct {
	ID          int64            `json:"id"`
	Status      int16            `json:"status"`
	Name        string           `json:"name"`
	Category    pgtype.Text      `json:"category"`
	Client      pgtype.Text      `json:"client"`
	Order       int32            `json:"order"`
	Highlighted bool             `json:"highlighted"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ProjectImage struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Url       string           `json:"url"`
	ProjectID int64            `json:"project_id"`
	Order     int32            `json:"order"`
	BlurHash  pgtype.Text      `json:"blur_hash"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type StaticText struct {
	ID        int64            `json:"id"`
	Key       string           `json:"key"`
	Label     string           `json:"label"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Testimonial struct {
	ID          int64            `json:"id"`
	FullName    string           `json:"full_name"`
	Profession  string           `json:"profession"`
	Testimonial string           `json:"testimonial"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID                    int64            `json:"id"`
	Name                  string           `json:"name"`
	Email                 string           `json:"email"`
	EmailVerifiedAt       pgtype.Timestamp `json:"email_verified_at"`
	Password              string           `json:"password"`
	PasswordResetRequired pgtype.Bool      `json:"password_reset_required"`
	ResetTokenHash        pgtype.Text      `json:"reset_token_hash"`
	ResetTokenExpiresAt   pgtype.Timestamp `json:"reset_token_expires_at"`
	RememberToken         pgtype.Text      `json:"remember_token"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type VisitorMessage struct {
	ID          int64            `json:"id"`
	Email       string           `json:"email"`
	Address     string           `json:"address"`
	Description string           `json:"description"`
	Seen        bool             `json:"seen"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
