// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_images.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectImage = `-- name: CreateProjectImage :one
INSERT INTO project_images (name, url, project_id, "order", blur_hash, highlighted, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, name, url, project_id, "order", blur_hash, created_at, updated_at, highlighted
`

type CreateProjectImageParams struct {
	Name        string      `json:"name"`
	Url         string      `json:"url"`
	ProjectID   int64       `json:"project_id"`
	Order       int32       `json:"order"`
	BlurHash    pgtype.Text `json:"blur_hash"`
	Highlighted bool        `json:"highlighted"`
}

func (q *Queries) CreateProjectImage(ctx context.Context, arg CreateProjectImageParams) (ProjectImage, error) {
	row := q.db.QueryRow(ctx, createProjectImage,
		arg.Name,
		arg.Url,
		arg.ProjectID,
		arg.Order,
		arg.BlurHash,
		arg.Highlighted,
	)
	var i ProjectImage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ProjectID,
		&i.Order,
		&i.BlurHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Highlighted,
	)
	return i, err
}

const deleteProjectImage = `-- name: DeleteProjectImage :exec
DELETE FROM project_images WHERE id = $1
`

func (q *Queries) DeleteProjectImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProjectImage, id)
	return err
}

const deleteProjectImagesByProjectID = `-- name: DeleteProjectImagesByProjectID :many
SELECT id, name, url, project_id, "order", blur_hash, created_at, updated_at, highlighted FROM project_images WHERE project_id = $1
`

func (q *Queries) DeleteProjectImagesByProjectID(ctx context.Context, projectID int64) ([]ProjectImage, error) {
	rows, err := q.db.Query(ctx, deleteProjectImagesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectImage
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.ProjectID,
			&i.Order,
			&i.BlurHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Highlighted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectImageByID = `-- name: GetProjectImageByID :one
SELECT id, name, url, project_id, "order", blur_hash, created_at, updated_at, highlighted FROM project_images WHERE id = $1
`

func (q *Queries) GetProjectImageByID(ctx context.Context, id int64) (ProjectImage, error) {
	row := q.db.QueryRow(ctx, getProjectImageByID, id)
	var i ProjectImage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ProjectID,
		&i.Order,
		&i.BlurHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Highlighted,
	)
	return i, err
}

const listProjectImageIDsByProjectID = `-- name: ListProjectImageIDsByProjectID :many
SELECT id FROM project_images WHERE project_id = $1
`

func (q *Queries) ListProjectImageIDsByProjectID(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listProjectImageIDsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectImagesByProjectID = `-- name: ListProjectImagesByProjectID :many
SELECT id, name, url, project_id, "order", blur_hash, created_at, updated_at, highlighted FROM project_images WHERE project_id = $1 ORDER BY "order" ASC
`

func (q *Queries) ListProjectImagesByProjectID(ctx context.Context, projectID int64) ([]ProjectImage, error) {
	rows, err := q.db.Query(ctx, listProjectImagesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectImage
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.ProjectID,
			&i.Order,
			&i.BlurHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Highlighted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unhighlightAllProjectImages = `-- name: UnhighlightAllProjectImages :exec
UPDATE project_images
SET highlighted = false,
    updated_at = NOW()
WHERE project_id = $1
`

func (q *Queries) UnhighlightAllProjectImages(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, unhighlightAllProjectImages, projectID)
	return err
}

const updateProjectImage = `-- name: UpdateProjectImage :exec
UPDATE project_images
SET name = $2,
    url = $3,
    "order" = $4,
    blur_hash = $5,
    highlighted = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateProjectImageParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Url         string      `json:"url"`
	Order       int32       `json:"order"`
	BlurHash    pgtype.Text `json:"blur_hash"`
	Highlighted bool        `json:"highlighted"`
}

func (q *Queries) UpdateProjectImage(ctx context.Context, arg UpdateProjectImageParams) error {
	_, err := q.db.Exec(ctx, updateProjectImage,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Order,
		arg.BlurHash,
		arg.Highlighted,
	)
	return err
}
