// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: static_texts.sql

package sqlc

import (
	"context"
)

const countStaticTexts = `-- name: CountStaticTexts :one
SELECT COUNT(*) FROM static_texts
`

func (q *Queries) CountStaticTexts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStaticTexts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStaticTextByID = `-- name: GetStaticTextByID :one
SELECT id, key, label, content, created_at, updated_at FROM static_texts WHERE id = $1
`

func (q *Queries) GetStaticTextByID(ctx context.Context, id int64) (StaticText, error) {
	row := q.db.QueryRow(ctx, getStaticTextByID, id)
	var i StaticText
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllStaticTexts = `-- name: ListAllStaticTexts :many
SELECT id, key, label, content, created_at, updated_at FROM static_texts ORDER BY created_at DESC
`

func (q *Queries) ListAllStaticTexts(ctx context.Context) ([]StaticText, error) {
	rows, err := q.db.Query(ctx, listAllStaticTexts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaticText
	for rows.Next() {
		var i StaticText
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaticTexts = `-- name: ListStaticTexts :many
SELECT id, key, label, content, created_at, updated_at FROM static_texts ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListStaticTextsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStaticTexts(ctx context.Context, arg ListStaticTextsParams) ([]StaticText, error) {
	rows, err := q.db.Query(ctx, listStaticTexts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaticText
	for rows.Next() {
		var i StaticText
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaticTextContent = `-- name: UpdateStaticTextContent :exec
UPDATE static_texts
SET content = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateStaticTextContentParams struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateStaticTextContent(ctx context.Context, arg UpdateStaticTextContentParams) error {
	_, err := q.db.Exec(ctx, updateStaticTextContent, arg.ID, arg.Content)
	return err
}
