// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: testimonials.sql

package sqlc

import (
	"context"
)

const countTestimonials = `-- name: CountTestimonials :one
SELECT COUNT(*) FROM testimonials
`

func (q *Queries) CountTestimonials(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTestimonials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTestimonial = `-- name: CreateTestimonial :one
INSERT INTO testimonials (full_name, profession, testimonial, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, full_name, profession, testimonial, status, created_at, updated_at
`

type CreateTestimonialParams struct {
	FullName    string `json:"full_name"`
	Profession  string `json:"profession"`
	Testimonial string `json:"testimonial"`
	Status      string `json:"status"`
}

func (q *Queries) CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (Testimonial, error) {
	row := q.db.QueryRow(ctx, createTestimonial,
		arg.FullName,
		arg.Profession,
		arg.Testimonial,
		arg.Status,
	)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Profession,
		&i.Testimonial,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTestimonial = `-- name: DeleteTestimonial :exec
DELETE FROM testimonials WHERE id = $1
`

func (q *Queries) DeleteTestimonial(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTestimonial, id)
	return err
}

const getTestimonialByID = `-- name: GetTestimonialByID :one
SELECT id, full_name, profession, testimonial, status, created_at, updated_at FROM testimonials WHERE id = $1
`

func (q *Queries) GetTestimonialByID(ctx context.Context, id int64) (Testimonial, error) {
	row := q.db.QueryRow(ctx, getTestimonialByID, id)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Profession,
		&i.Testimonial,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicTestimonials = `-- name: ListPublicTestimonials :many
SELECT id, full_name, profession, testimonial, status, created_at, updated_at FROM testimonials WHERE status = 'ready' ORDER BY created_at DESC
`

func (q *Queries) ListPublicTestimonials(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listPublicTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Testimonial
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Profession,
			&i.Testimonial,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestimonials = `-- name: ListTestimonials :many
SELECT id, full_name, profession, testimonial, status, created_at, updated_at FROM testimonials ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListTestimonialsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTestimonials(ctx context.Context, arg ListTestimonialsParams) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listTestimonials, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Testimonial
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Profession,
			&i.Testimonial,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTestimonial = `-- name: UpdateTestimonial :exec
UPDATE testimonials
SET full_name = $2,
    profession = $3,
    testimonial = $4,
    status = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTestimonialParams struct {
	ID          int64  `json:"id"`
	FullName    string `json:"full_name"`
	Profession  string `json:"profession"`
	Testimonial string `json:"testimonial"`
	Status      string `json:"status"`
}

func (q *Queries) UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) error {
	_, err := q.db.Exec(ctx, updateTestimonial,
		arg.ID,
		arg.FullName,
		arg.Profession,
		arg.Testimonial,
		arg.Status,
	)
	return err
}
