// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, password_reset_required, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, name, email, email_verified_at, password, password_reset_required, reset_token_hash, reset_token_expires_at, remember_token, created_at, updated_at
`

type CreateUserParams struct {
	Name                  string      `json:"name"`
	Email                 string      `json:"email"`
	Password              string      `json:"password"`
	PasswordResetRequired pgtype.Bool `json:"password_reset_required"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PasswordResetRequired,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.PasswordResetRequired,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.RememberToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified_at, password, password_reset_required, reset_token_hash, reset_token_expires_at, remember_token, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.PasswordResetRequired,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.RememberToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified_at, password, password_reset_required, reset_token_hash, reset_token_expires_at, remember_token, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.PasswordResetRequired,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.RememberToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByResetTokenHash = `-- name: GetUserByResetTokenHash :one
SELECT id, name, email, email_verified_at, password, password_reset_required, reset_token_hash, reset_token_expires_at, remember_token, created_at, updated_at FROM users WHERE reset_token_hash = $1 AND reset_token_expires_at > NOW()
`

func (q *Queries) GetUserByResetTokenHash(ctx context.Context, resetTokenHash pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByResetTokenHash, resetTokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.PasswordResetRequired,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.RememberToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, email_verified_at, password, password_reset_required, reset_token_hash, reset_token_expires_at, remember_token, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.Password,
			&i.PasswordResetRequired,
			&i.ResetTokenHash,
			&i.ResetTokenExpiresAt,
			&i.RememberToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $2, email = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.ID, arg.Name, arg.Email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2,
    password_reset_required = false,
    reset_token_hash = NULL,
    reset_token_expires_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserResetToken = `-- name: UpdateUserResetToken :exec
UPDATE users
SET reset_token_hash = $2,
    reset_token_expires_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserResetTokenParams struct {
	ID                  int64            `json:"id"`
	ResetTokenHash      pgtype.Text      `json:"reset_token_hash"`
	ResetTokenExpiresAt pgtype.Timestamp `json:"reset_token_expires_at"`
}

func (q *Queries) UpdateUserResetToken(ctx context.Context, arg UpdateUserResetTokenParams) error {
	_, err := q.db.Exec(ctx, updateUserResetToken, arg.ID, arg.ResetTokenHash, arg.ResetTokenExpiresAt)
	return err
}
