// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitor_messages.sql

package sqlc

import (
	"context"
)

const countVisitorMessages = `-- name: CountVisitorMessages :one
SELECT COUNT(*) FROM visitor_messages
`

func (q *Queries) CountVisitorMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVisitorMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVisitorMessage = `-- name: CreateVisitorMessage :one
INSERT INTO visitor_messages (email, address, description, seen, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, email, address, description, seen, created_at, updated_at
`

type CreateVisitorMessageParams struct {
	Email       string `json:"email"`
	Address     string `json:"address"`
	Description string `json:"description"`
	Seen        bool   `json:"seen"`
}

func (q *Queries) CreateVisitorMessage(ctx context.Context, arg CreateVisitorMessageParams) (VisitorMessage, error) {
	row := q.db.QueryRow(ctx, createVisitorMessage,
		arg.Email,
		arg.Address,
		arg.Description,
		arg.Seen,
	)
	var i VisitorMessage
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Address,
		&i.Description,
		&i.Seen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVisitorMessage = `-- name: DeleteVisitorMessage :exec
DELETE FROM visitor_messages WHERE id = $1
`

func (q *Queries) DeleteVisitorMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVisitorMessage, id)
	return err
}

const listVisitorMessages = `-- name: ListVisitorMessages :many
SELECT id, email, address, description, seen, created_at, updated_at FROM visitor_messages ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListVisitorMessagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVisitorMessages(ctx context.Context, arg ListVisitorMessagesParams) ([]VisitorMessage, error) {
	rows, err := q.db.Query(ctx, listVisitorMessages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisitorMessage
	for rows.Next() {
		var i VisitorMessage
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Address,
			&i.Description,
			&i.Seen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
